version: '3.5'

services:
    nginxproxy:
        container_name: nginxproxy
        image: jwilder/nginx-proxy:alpine
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs:ro
        networks: 
            - webproxy

networks: 
    webproxy:
        name: webproxy