version: '3.5'

services:
    traefik:
        container_name: traefik_proxy
        image: traefik
        #restart: always
        ports:
            - "81:80"
            - "8000:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml
            - ./acme.json:/acme.json
            - ./certs:/certs
            - ./domains:/domains
        networks:
            - webproxy

networks:
    webproxy:
        name: webproxy
